name: 'fintrade'
version: '1.0.0'
config-version: 2

profile: 'fintrade'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  fintrade:
    staging:
      +schema: staging
      +materialized: view
    core:
      +schema: core
      +materialized: view
    mart:
      +schema: mart
      +materialized: table
